include ${SEPINC}/SEP.top

#General stuff
BINDIR=   #BINARY DIRECTORY (defaults to .)
SRCDIR=   #BINARY DIRECTORY (defaults to .)
OBJDIR=   #BINARY DIRECTORY (defaults to .)


#C linking
UCFLAGS =  #flags to send the  (eg -ansi)
UCINCLUDES =  #include flags (eg -I/usr/local/include)
UCLIBDIRS  =  #directorys containing libraries (eg /usr/local/lib)
UCLIBS     =  #extra libraries (eg -lmy_lib)

#F90 linking
UF90FLAGS =  #flags to send the  (eg -mp)
UF90INCLUDES =  #include flags (eg -I/usr/local/include)
UF90LIBDIRS  =  #directorys containing libraries (eg /usr/local/lib)
UF90LIBS     =  #extra libraries (eg -lmy_lib)

#F77 linking
UF77FLAGS =  #flags to send the  (eg -mp)
UF77NCLUDES =  #include flags (eg -I/usr/local/include)
UF77LIBDIRS  =  #directorys containing libraries (eg /usr/local/lib)
UF770LIBS     =  #extra libraries (eg -lmy_lib)


include ${SEPINC}/SEP.bottom
